### ISSUE TITLE
How does BCFier identify and isolate components

### ISSUE THREAD

**Issue by alexandernesbitt** [teocomi/BCFier#9]
Hi Matteo,

Could you please advise as to what data BCFier is reading from the BCF to identify and isolate components within Revit?

I initially suspected it used the IfcGUID generated on export, after testing, It seems to be the element ID. Is this correct?

Thanks,
Alex

**Comment by teocomi** [comment]
Hi Alex,
the elements are stored with their IfcGUID and Revit ID in the bcf viewpoint. But actually BCFier only uses the IfcGUID. In order to avoid redundant information when creating a view BCFier does the following:
- if the number of visible elements > hidden ones: stores all the hidden and selected elements (with relative visible/selected flags)
- if the number of visible elements < hidden ones: stores all the visible elements (with relative visible/selected flags)

The actual code is in:
https://github.com/teocomi/BCFier/blob/master/Bcfier.Revit/RevitWindow.xaml.cs

There might be issues with GUIDs changing when importing geometry from one software to another, also the way components are currently being stored in viewpoints is still being discussed in the BCF group as the current implementation causes performance/filesize issues: https://github.com/BuildingSMART/BCF-XML/issues/66

Let me know if you have other questions.
